services:
  - type: web
    name: corsehub
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --prefix server
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
    rootDir: ./
    disks:
      - name: data
        mountPath: /var/data
        sizeGB: 1
